### ISSUE TITLE
🧐[问题] How to use with next.js

### ISSUE THREAD

**Issue by toqitahamid** [ant-design/ant-design-pro-layout#432]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

I used this template (https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) with Ant Design Pro Layout. 

My index.js - 

```javascript 
import ProLayout from '@ant-design/pro-layout';
import React from "react";


export default () => (
    <ProLayout/>
)
```

I am getting this error - 

```javascript 
Invalid or unexpected token
/home/toqi/WebstormProjects/grocery-admin/node_modules/antd/lib/style/index.less:1
@import './themes/index';
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/toqi/WebstormProjects/grocery-admin/node_modules/antd/lib/layout/style/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/toqi/WebstormProjects/grocery-admin/node_modules/@ant-design/pro-layout/lib/BasicLayout.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

**Comment by pahaz** [comment]
Yes, it's hard to use `ant-design-pro-layout` with `next.js`.

I know at least this limitations:
 - SSR doesn't work (you should use `{ ssr: false }`)
 - If you want to use `.less` and `.css` in `next.js` app you should hack a `webpack` config (or just use only less without style import feature).

I have some less hackable example here: https://github.com/8iq/nodejs-hackathon-boilerplate-starter-kit/tree/master/apps/_example04antpro

**Comment by toqitahamid** [comment]
Thanks for the suggestions!
